//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpaquePesosSierraBlue.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SierraBlueDB : DbContext
    {
        public SierraBlueDB()
            : base("name=SierraBlueDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Calibre> Calibres { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Empaque> Empaques { get; set; }
        public virtual DbSet<LoteCultivo> LotesCultivos { get; set; }
        public virtual DbSet<Presentacion> Presentaciones { get; set; }
        public virtual DbSet<Productor> Productores { get; set; }
        public virtual DbSet<Recepcion> Recepciones { get; set; }
        public virtual DbSet<Variedad> Variedades { get; set; }
    }
}
