//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpaquePesosSierraBlue.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variedad
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Iniciales { get; set; }
        public string Estado { get; set; }
        public Nullable<int> ProductorId { get; set; }
    
        public virtual Productor Productor { get; set; }
    }
}
