//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecepciónPesosSierraBlue.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;

    public partial class Recepcion
    {
        public int Id { get; set; }
        public System.DateTime FechaYHora { get; set; }
        public string Puerto { get; set; }
        public string Productor { get; set; }
        public string Variedad { get; set; }
        public string LoteCultivo { get; set; }
        public string LotePoscosecha { get; set; }
        public string Categoria { get; set; }
        public float Peso { get; set; }
        [NotMapped]
        public string PesoTexto { get; set;}
        [NotMapped]
        public string IncialesProductor { get; set; }
        [NotMapped]
        public string InicialesVariedad { get; set; }
    }
}
